"""
schemas about authentification
"""

from pydantic import BaseModel
from typing import Optional

# as fastAPI helps to take care of headder, route, concurrency, json encoding/decoding ...
# so only define: every request/response: all variables(its type)
class LoginRequest(BaseModel):
    """login request"""
    device_id: str  # deviceID generated by client


class LoginResponse(BaseModel):
    """login response"""
    user_id: int
    token: str
    is_new_user: bool  # if is a new user


class TokenData(BaseModel):
    """Token decoded data"""
    user_id: Optional[int] = None