"""
user table model
to store user/device info
"""

from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.orm import relationship

from app.db.database import Base


class User(Base):
    """user table"""
    
    __tablename__ = "users"
    
    # PK
    id = Column(Integer, primary_key=True, index=True)
    
    # device id(unique, generated by client and lasts)
    device_id = Column(String(64), unique=True, nullable=False, index=True)
    
    # timestamp
    created_at = Column(DateTime, default=datetime.utcnow)
    last_login_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # relation: a user can have multi saves
    saves = relationship("Save", back_populates="user", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<User(id={self.id}, device_id={self.device_id[:8]}...)>"
